In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests

# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Coihaique,CL,2022-09-17 15:47:13,-45.5752,-72.0662,40.95,52,20,4.61
1,1,Punta Arenas,CL,2022-09-17 15:44:55,-53.1500,-70.9167,46.51,42,0,20.71
2,2,Bluff,NZ,2022-09-17 15:47:13,-46.6000,168.3333,42.37,83,97,7.27
3,3,Albany,US,2022-09-17 15:43:56,42.6001,-73.9662,64.31,64,100,2.01
4,4,Busselton,AU,2022-09-17 15:47:14,-33.6500,115.3333,51.15,89,20,4.99

In [3]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
    # the above can also be used [max(temp, 0) for temp in max_temp]

In [5]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
# Google heatmaps do not plot negative numbers. If you have a maximum temperature that is less than 0 Â°F, then you will 
# get an 
# InvalidWeightException 
# error for this is the following line of code: 
# heat_layer = gmaps.heatmap_layer(locations, weights=temps)

In [7]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable with a zoom level
fig = fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variablw with max_intensity and point_radius
heat_layer = gmaps.heatmap_layer(locations, weights=[
    max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Heatmap of Wind Speed Heatmap
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [12]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
7,7,Atchison,US,2022-09-17 15:47:15,39.5630,-95.1216,79.32,87,80,11.18
8,8,Hilo,US,2022-09-17 15:45:32,19.7297,-155.0900,83.28,80,40,6.91
10,10,Yuli,NG,2022-09-17 15:47:16,9.6989,10.2744,76.86,80,99,2.59
11,11,Acapulco,MX,2022-09-17 15:47:17,16.8634,-99.8901,75.78,96,100,14.27
15,15,Butaritari,KI,2022-09-17 15:47:18,3.0707,172.7902,82.09,66,54,12.53
16,16,Filadelfia,US,2022-09-17 15:44:50,39.9523,-75.1638,80.11,64,75,8.05
18,18,Saint Pete Beach,US,2022-09-17 15:47:19,27.7253,-82.7412,85.21,71,0,10.36
20,20,Georgetown,MY,2022-09-17 15:44:47,5.4112,100.3354,84.13,88,20,3.44
21,21,Jamestown,US,2022-09-17 15:47:20,42.0970,-79.2353,75.52,59,14,4.00
26,26,Soyo,AO,2022-09-17 15:47:22,-6.1349,12.3689,75.88,77,83,8.25

In [13]:
preferred_cities_df.count()

City_ID       203
City          203
Country       203
Date          203
Lat           203
Lng           203
Max Temp      203
Humidity      203
Cloudiness    203
Wind Speed    203
dtype: int64

In [14]:
preferred_cities_df.isnull().sum()

City_ID       0
City          0
Country       0
Date          0
Lat           0
Lng           0
Max Temp      0
Humidity      0
Cloudiness    0
Wind Speed    0
dtype: int64

In [15]:
preferred_cities_df.notnull().sum()

City_ID       203
City          203
Country       203
Date          203
Lat           203
Lng           203
Max Temp      203
Humidity      203
Cloudiness    203
Wind Speed    203
dtype: int64

In [16]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

                City Country  Max Temp      Lat       Lng Hotel Name
7           Atchison      US     79.32  39.5630  -95.1216
8               Hilo      US     83.28  19.7297 -155.0900
10              Yuli      NG     76.86   9.6989   10.2744
11          Acapulco      MX     75.78  16.8634  -99.8901
15        Butaritari      KI     82.09   3.0707  172.7902
16        Filadelfia      US     80.11  39.9523  -75.1638
18  Saint Pete Beach      US     85.21  27.7253  -82.7412
20        Georgetown      MY     84.13   5.4112  100.3354
21         Jamestown      US     75.52  42.0970  -79.2353
26              Soyo      AO     75.88  -6.1349   12.3689

In [17]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
        
# Grab the first hotel from the results and store the name.
    try:
        print(f"Closest hotel is {hotels['results'][0]['name']}.")
        hotel_df.loc[index, 'Hotel Name'] = hotels['results'][0]['name']
        
    except (IndexError):
        print("Hotel not found... skipping.")
        
    print("------------")

Closest hotel is Quality Inn, Atchison.
------------
Closest hotel is Hilo Hawaiian Hotel.
------------
Hotel not found... skipping.
------------
Closest hotel is HS Hotsson Smart Acapulco.
------------
Closest hotel is Isles Sunset Lodge.
------------
Closest hotel is The Ritz-Carlton, Philadelphia.
------------
Closest hotel is Sirata Beach Resort.
------------
Closest hotel is Cititel Penang.
------------
Closest hotel is Hampton Inn & Suites Jamestown.
------------
Closest hotel is Hospedaria ndozi'ame.
------------
Closest hotel is Suoxing Hotel.
------------
Closest hotel is Aldea del Bazar Hotel and Spa.
------------
Closest hotel is Bonthe Holiday Village.
------------
Closest hotel is Aung Naing Thu Motel.
------------
Closest hotel is Ss garden hotel & restaurant.
------------
Closest hotel is Bora-Bora Pearl Beach Resort & Spa.
------------
Closest hotel is Amazigh Hostel.
------------
Closest hotel is Fengshui Residence.
------------
Closest hotel is Leumerus Bungalows.
------------
Closest hotel is Kimbo Hotel.
------------
Closest hotel is Cortez Malaga Techy Caroly.
------------
Closest hotel is Lorengau Harbourside Hotel.
------------
Closest hotel is Six Acres Bed & Breakfast.
------------
Closest hotel is I-Destiny Gallery Resort.
------------
Closest hotel is Tour Eiffel Hotel Benin.
------------
Closest hotel is Hacienda Gracia.
------------
Hotel not found... skipping.
------------
Closest hotel is ALETHEIA Appartement Sinnamary.
------------
Closest hotel is Grand Kecubung Hotel.
------------
Closest hotel is Mini Central.
------------
Closest hotel is Auberge les abou.
------------
Closest hotel is Pension Oaoa.
------------
Closest hotel is Scoop Guest House.
------------
Closest hotel is Islazul Niquero.
------------
Closest hotel is Av. Castelo Branco. GinÃ¡sio Ermelino vieira..
------------
Closest hotel is Bungalow 63.
------------
Closest hotel is Hotel do Campo.
------------
Closest hotel is Osprey Beach Hotel.
------------
Closest hotel is Aviador Hotel Boutique.
------------
Closest hotel is Villa Raphael Resort.
------------
Closest hotel is Quinta da Meia Eira.
------------
Closest hotel is Sapriadi Appy.
------------
Closest hotel is Conquistador Hotel.
------------
Closest hotel is Lidera.
------------
Hotel not found... skipping.
------------
Closest hotel is Pirineos.
------------
Closest hotel is HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel.
------------
Closest hotel is xamdihotelresturant114.
------------
Closest hotel is HÃ´tel Hiva Oa Hanakee Lodge.
------------
Closest hotel is Sherwood Motel.
------------
Closest hotel is TE'AMO Entertainment Park.
------------
Closest hotel is Kost Pria.
------------
Closest hotel is Grage Hotel Bengkulu.
------------
Closest hotel is Nusa Island Retreat.
------------
Closest hotel is Nuli Sapi.
------------
Closest hotel is Balneario Rio el Paraiso.
------------
Closest hotel is HÃ´tel Chat Rouge.
------------
Closest hotel is Ghanzi Farmhouse.
------------
Closest hotel is Welcomhotel By ITC Hotels, Bay Island, Port Blair.
------------
Closest hotel is Sunset Inn.
------------
Closest hotel is Hotel Wixel.
------------
Hotel not found... skipping.
------------
Closest hotel is Balandra Hotel.
------------
Hotel not found... skipping.
------------
Closest hotel is Arribas Sintra Hotel.
------------
Closest hotel is Yarada Jungle Beach Resorts.
------------
Closest hotel is Sur Plaza Hotel.
------------
Closest hotel is Hotel Ark 21.
------------
Closest hotel is Casa Maquia.
------------
Hotel not found... skipping.
------------
Closest hotel is ÙØ±ÙØ´Ú¯Ø§Ù Ø²ÙØ¨ÛÙ.
------------
Closest hotel is Hotel Tesoro Los Cabos.
------------
Closest hotel is Samson Hotel.
------------
Closest hotel is Vahmoneh Lodge Vanimo.
------------
Closest hotel is Katsuura Hotel Mikazuki.
------------
Closest hotel is Hotel Xaguate.
------------
Closest hotel is Siang Guest House.
------------
Closest hotel is SEGAYA PROPERTY.
------------
Closest hotel is Protea Hotel by Marriott Zambezi River Lodge.
------------
Closest hotel is castelo pizzaria.
------------
Closest hotel is Eka RESIDENCY A/C.
------------
Closest hotel is Hotel Residencial Centro.
------------
Closest hotel is Screensaver.
------------
Closest hotel is Hotel negin bojnourd.
------------
Closest hotel is Kamaneahn Hotel Inc.
------------
Closest hotel is JABIR HOTEL.
------------
Closest hotel is Hotel Duyung Permai 2.
------------
Closest hotel is Ganpati Guest House.
------------
Closest hotel is Inubosaki Kanko Hotel.
------------
Closest hotel is Sevgi Otel.
------------
Closest hotel is Agapita M. Nicart.
------------
Closest hotel is Hotel Porto Santo & Spa.
------------
Closest hotel is El rranchito michuacan de ocampos.
------------
Closest hotel is Best Western Plus South Coast Inn.
------------
Closest hotel is HOTEL ISABELA.
------------
Closest hotel is Southern Beach Hotel & Resort Okinawa.
------------
Closest hotel is Pestana Bahia Praia.
------------
Closest hotel is Hotel Ordem de Santiago.
------------
Closest hotel is HOTEL BOURAQ INDAH PERMAI.
------------
Closest hotel is Hotel Saigon-PT.
------------
Closest hotel is Minshuku Agaihama.
------------
Closest hotel is ZINGARA 76ft Catamaran, full crew-all included.
------------
Closest hotel is Tamir Hotel Ltd.
------------
Closest hotel is La Villa Mahatsara.
------------
Closest hotel is Casa de Provincia.
------------
Closest hotel is HÃ´tel Le Dronmi.
------------
Closest hotel is SanBiz Lodge.
------------
Closest hotel is Tiara Labuan Hotel.
------------
Closest hotel is Hotel Flamingo.
------------
Closest hotel is Shams hotel.
------------
Closest hotel is Hills & Valley Adventure Resort.
------------
Closest hotel is Hotel TomatÃ£o.
------------
Closest hotel is Hotel Manglares.
------------
Closest hotel is Fairfield Inn & Suites by Marriott Lake Charles Sulphur.
------------
Closest hotel is hotel la terminal.
------------
Closest hotel is Birjand Tourist Hotel.
------------
Closest hotel is Ruby Backpackers.
------------
Closest hotel is Tarawa Boutique Hotel.
------------
Closest hotel is Motel 6 Sinton, TX.
------------
Closest hotel is LT Aparthotel.
------------
Closest hotel is Aracati Hotel.
------------
Closest hotel is LE SAMANA.
------------
Closest hotel is Dadi Lodge.
------------
Closest hotel is Nag Aespen.
------------
Closest hotel is Lamu House.
------------
Closest hotel is Ø­Ø§ÙØ¯ ÙØ­ÙØ¯ ÙÙØ±.
------------
Closest hotel is Nuevo Hotel Coromoto.
------------
Closest hotel is INN NEW HORIZON.
------------
Closest hotel is Fuente del Guania Hotel de Lujo.
------------
Hotel not found... skipping.
------------
Closest hotel is Wolong Village.
------------
Closest hotel is Tanna Lodge.
------------
Closest hotel is Delong Hotel.
------------
Closest hotel is Salinas do Maragogi All Inclusive Resort.
------------
Closest hotel is JM Lodge.
------------
Closest hotel is Hotel Europe Kropotkin.
------------
Hotel not found... skipping.
------------
Closest hotel is La Tahzan Guest House.
------------
Closest hotel is Gran Tacande Wellness & Relax.
------------
Closest hotel is Blue Ridge Beach Resort.
------------
Closest hotel is Moland Beach Resort.
------------
Closest hotel is Green leaf.
------------
Hotel not found... skipping.
------------
Closest hotel is Kinh Do Hotel.
------------
Closest hotel is TumbleWeed RV Park.
------------
Closest hotel is Low Cost Housing Estate.
------------
Closest hotel is ÙÙØ¯Ù Ø§ÙÙØ±Ø¯ÙØ³.
------------
Hotel not found... skipping.
------------
Closest hotel is Nam Long Hotel.
------------
Closest hotel is ABS Hotel.
------------
Closest hotel is The Walper Hotel.
------------
Closest hotel is Mahmoudâs Home.
------------
Closest hotel is Atlantis Hotel.
------------
Closest hotel is Hotel Porta Fira.
------------
Closest hotel is HOTEL MYTH-W ï¼ããã« ãã¤ã¹ ãããªã¥ã¼ï¼.
------------
Closest hotel is Hotel y restaurante "El Diamante".
------------
Closest hotel is Hanks place.
------------
Closest hotel is Groote Eylandt Lodge.
------------
Closest hotel is K.korabay 28A.
------------
Closest hotel is SAIVEN MALL (SAIVEN C.A.).
------------
Closest hotel is Base Lodging.
------------
Closest hotel is Maringe Lagoon Lodge.
------------

Closest hotel is Heritage Park Hotel.
------------
Closest hotel is Valle Aridane.
------------
Closest hotel is Radisson Grenada Beach Resort.
------------
Closest hotel is Nancy Montanes Bernardo.
------------
Closest hotel is La Ode Husein.
------------
Closest hotel is Gaur Guest House.
------------
Closest hotel is Kaosai Country Club.
------------
Closest hotel is Hotel Boutique El Turista.
------------
Closest hotel is Guest House Epervier.
------------
Closest hotel is Villa Rica Park Hotel GMR.
------------
Closest hotel is Posada Villa Nela.
------------
Closest hotel is Divi Flamingo Beach Resort & Casino.
------------
Closest hotel is Ãzenler Residence Otel, ÅÄ±rnak Silopi.
------------
Closest hotel is Axim Beach Resort And Spa.
------------
Closest hotel is Shimoda Tokyu Hotel.
------------
Closest hotel is Samparada & Gestiada Residences.
------------
Closest hotel is Green Valley.
------------
Closest hotel is Cruzeiro Hotel.
------------
Closest hotel is Haji laloo memon house.
------------
Closest hotel is HÃ´tel Les Jardins De Sainte Maxime.
------------
Closest hotel is è¡æ©å¸ç ä¿®ã»ã³ã¿ã¼ ããããã¢.
------------
Closest hotel is Ted McQuinn Trust.
------------
Hotel not found... skipping.
------------
Closest hotel is American Eagle Inn.
------------
Closest hotel is Vuong Hoan 2.
------------
Closest hotel is Feifan Chengpin Hotel Shanmutang.
------------
Closest hotel is Medhufushi Island Resort.
------------
Closest hotel is MR-SAGAR_KUMAR_RTRâ¢.
------------
Hotel not found... skipping.
------------
Closest hotel is Hotel Juba.
------------
Closest hotel is Seagulls Inn Namatani.
------------
Closest hotel is Hotel Alejandro I.
------------
Closest hotel is Phama Lodge.
------------
Closest hotel is Apartment Av. Castelao.
------------
Closest hotel is Aipana Plaza Hotel.
------------
Closest hotel is Salinas Park Resort MaÃ§arico AP101.
------------
Closest hotel is Auto Hotel El SoÃ±ador.
------------
Closest hotel is Bus group international.
------------
Closest hotel is Niyama Private Islands Maldives.
------------
Closest hotel is Artemis Otel.
------------
Closest hotel is Hotel Olako.
------------

In [18]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
7,Atchison,US,79.32,39.5630,-95.1216,"Quality Inn, Atchison"
8,Hilo,US,83.28,19.7297,-155.0900,Hilo Hawaiian Hotel
10,Yuli,NG,76.86,9.6989,10.2744,
11,Acapulco,MX,75.78,16.8634,-99.8901,HS Hotsson Smart Acapulco
15,Butaritari,KI,82.09,3.0707,172.7902,Isles Sunset Lodge
16,Filadelfia,US,80.11,39.9523,-75.1638,"The Ritz-Carlton, Philadelphia"
18,Saint Pete Beach,US,85.21,27.7253,-82.7412,Sirata Beach Resort
20,Georgetown,MY,84.13,5.4112,100.3354,Cititel Penang
21,Jamestown,US,75.52,42.0970,-79.2353,Hampton Inn & Suites Jamestown
26,Soyo,AO,75.88,-6.1349,12.3689,Hospedaria ndozi'ame

In [19]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [20]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [21]:
# Using the template add city name, the country code and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))