## Deliverable 2. Create a Customer Travel Destinations Map.

In [3]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [6]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Majene,ID,-3.5403,118.9707,79.88,84,100,1.54,overcast clouds
1,1,Bluff,NZ,-46.6000,168.3333,46.80,83,100,8.48,overcast clouds
2,2,Ushuaia,AR,-54.8000,-68.3000,37.06,75,0,8.05,clear sky
3,3,Jamestown,US,42.0970,-79.2353,69.51,75,0,6.91,clear sky
4,4,Kapaa,US,22.0752,-159.3190,77.32,85,20,10.36,few clouds
5,5,Bolobo,CD,-2.1667,16.2333,83.89,60,100,1.66,light rain
6,6,Sitka,US,57.0531,-135.3300,55.29,88,100,4.61,light rain
7,7,Busselton,AU,-33.6500,115.3333,54.32,78,100,8.72,overcast clouds
8,8,Port Elizabeth,ZA,-33.9180,25.5701,62.10,88,40,12.66,scattered clouds
9,9,Mataura,NZ,-46.1927,168.8643,46.47,89,99,4.07,overcast clouds

In [7]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [8]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Majene,ID,-3.5403,118.9707,79.88,84,100,1.54,overcast clouds
4,4,Kapaa,US,22.0752,-159.3190,77.32,85,20,10.36,few clouds
5,5,Bolobo,CD,-2.1667,16.2333,83.89,60,100,1.66,light rain
13,13,Gayeri,BF,12.6497,0.4931,85.82,62,100,8.05,light rain
14,14,Atuona,PF,-9.8000,-139.0333,76.44,76,23,24.67,light rain
17,17,Potiskum,NG,11.7091,11.0694,85.48,55,79,5.08,light rain
19,19,Morant Bay,JM,17.8815,-76.4093,82.71,75,17,5.84,few clouds
21,21,Providencia,MX,28.7167,-111.5833,82.45,57,0,6.08,clear sky
22,22,Sao Filipe,CV,14.8961,-24.4956,78.01,75,48,7.20,scattered clouds
25,25,Kaniama,CD,-7.5667,24.1833,86.90,40,90,3.04,light rain

In [9]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                1
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [14]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df = preferred_cities_df.dropna()
preferred_cities_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Majene,ID,-3.5403,118.9707,79.88,84,100,1.54,overcast clouds
4,4,Kapaa,US,22.0752,-159.3190,77.32,85,20,10.36,few clouds
5,5,Bolobo,CD,-2.1667,16.2333,83.89,60,100,1.66,light rain
13,13,Gayeri,BF,12.6497,0.4931,85.82,62,100,8.05,light rain
14,14,Atuona,PF,-9.8000,-139.0333,76.44,76,23,24.67,light rain
...,...,...,...,...,...,...,...,...,...,...
699,699,Tual,ID,-5.6667,132.7500,81.75,77,100,13.18,overcast clouds
700,700,Mundo Nuevo,MX,18.7000,-95.5000,76.30,93,100,7.52,overcast clouds
701,701,Kontagora,NG,10.3999,5.4695,82.44,69,46,3.02,light rain
702,702,Ponta Delgada,PT,37.7333,-25.6667,77.72,73,20,8.05,few clouds
703,703,Biak,ID,-0.9131,122.8766,77.23,83,100,3.29,overcast clouds

In [17]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Majene,ID,79.88,overcast clouds,-3.5403,118.9707,
4,Kapaa,US,77.32,few clouds,22.0752,-159.3190,
5,Bolobo,CD,83.89,light rain,-2.1667,16.2333,
13,Gayeri,BF,85.82,light rain,12.6497,0.4931,
14,Atuona,PF,76.44,light rain,-9.8000,-139.0333,
17,Potiskum,NG,85.48,light rain,11.7091,11.0694,
19,Morant Bay,JM,82.71,few clouds,17.8815,-76.4093,
21,Providencia,MX,82.45,clear sky,28.7167,-111.5833,
22,Sao Filipe,CV,78.01,scattered clouds,14.8961,-24.4956,
25,Kaniama,CD,86.90,light rain,-7.5667,24.1833,

In [18]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        print(f"Closest hotel is {hotels['results'][0]['name']}.")
        hotel_df.loc[index, 'Hotel Name'] = hotels['results'][0]['name']
        
    except (IndexError):
        print("Hotel not found... skipping.")
        
    print("------------")

Closest hotel is Kost Putri RABBANI.
------------
Closest hotel is Sheraton Kauai Coconut Beach Resort.
------------
Closest hotel is Hotel de Stephen.
------------
Hotel not found... skipping.
------------
Closest hotel is Hôtel Hiva Oa Hanakee Lodge.
------------
Closest hotel is Tamir Hotel Ltd.
------------
Closest hotel is Whispering Bamboo Cove Resort.
------------
Hotel not found... skipping.
------------
Closest hotel is Hotel Xaguate.
------------
Hotel not found... skipping.
------------
Closest hotel is Colinas de Matasiete.
------------
Closest hotel is Scoop Guest House.
------------
Closest hotel is J'AIME ATTOBRO, (Mon Village).
------------
Hotel not found... skipping.
------------
Closest hotel is Motel 6 Sinton, TX.
------------
Closest hotel is Railway motel.
------------
Closest hotel is Yusif 10 A.
------------
Closest hotel is Guest house.
------------
Closest hotel is Quinta da Meia Eira.
------------
Closest hotel is Marriott's Ocean Pointe.
------------
Closest hotel is Axim Beach Resort And Spa.
------------
Closest hotel is DoubleFAG.
------------
Closest hotel is Cititel Penang.
------------
Hotel not found... skipping.
------------
Closest hotel is Mini Central.
------------
Closest hotel is Nuli Sapi.
------------
Closest hotel is Salinas do Maragogi All Inclusive Resort.
------------
Closest hotel is Sirius.
------------
Hotel not found... skipping.
------------
Hotel not found... skipping.
------------
Closest hotel is Hotel Fessla.
------------
Closest hotel is Apartment Av. Castelao.
------------
Closest hotel is Mishti Polutry Farm.
------------
Closest hotel is Shantou Chaoyang Donghui Hotel.
------------
Closest hotel is Hilo Hawaiian Hotel.
------------
Closest hotel is Hotel do Campo.
------------
Closest hotel is Hotel Mirage.
------------
Closest hotel is สวนป่ารีสอร์ท.
------------
Closest hotel is Karst Youth Hostel.
------------
Closest hotel is Fengshui Residence.
------------
Closest hotel is Korolevskiy Dvor.
------------
Closest hotel is Shwe Phyu Hotel.
------------
Closest hotel is Balneario Rio el Paraiso.
------------
Closest hotel is ALETHEIA Appartement Sinnamary.
------------
Closest hotel is Hotel Gualok.
------------
Closest hotel is Isles Sunset Lodge.
------------
Closest hotel is Remont Komp'yutera.
------------
Closest hotel is Copamarina Beach Resort & Spa.
------------
Closest hotel is Kimbo Hotel.
------------
Closest hotel is Waigo Splash Hotel.
------------
Closest hotel is DH international Hotel.
------------
Closest hotel is Hotel Silva.
------------
Closest hotel is castelo pizzaria.
------------
Closest hotel is OlusHome.
------------
Hotel not found... skipping.
------------
Closest hotel is HOTEL ISABELA.
------------
Closest hotel is Agan-Hotel.
------------
Closest hotel is Otel restoran.
------------
Closest hotel is Steve Walden and Emma Sison-Walden Residence.
------------
Closest hotel is Complexe.
------------
Closest hotel is Villa Park Hotel | Natal.
------------
Hotel not found... skipping.
------------
Closest hotel is Katsuura Hotel Mikazuki.
------------
Closest hotel is Guest Hotel.
------------
Closest hotel is Atlantis Hotel.
------------
Closest hotel is Oceano.
------------
Closest hotel is Savli Resort/Hotel - Shrivardhan.
------------
Closest hotel is INN NEW HORIZON.
------------
Closest hotel is Belle Maison Hadana Hoi An managed by H&K Hospitality.
------------
Closest hotel is Patel Residency.
------------
Closest hotel is Bungalow 63.
------------
Closest hotel is Surpanch saab ki vatika.
------------
Closest hotel is Hotel Tesoro Los Cabos.
------------
Closest hotel is SEGAYA PROPERTY.
------------
Closest hotel is ASTON Cirebon Hotel & Convention Center.
------------
Closest hotel is Fort Johnstone Hotel.
------------
Closest hotel is Pestana Bahia Praia.
------------
Closest hotel is Hotel Ambulu Jember.
------------
Closest hotel is Hotel GSA.
------------
Closest hotel is HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel.
------------
Closest hotel is Lírio Mendes.
------------
Closest hotel is Umit.
------------
Closest hotel is Riviera Royal Hotel.
------------
Closest hotel is Raybow International Hotel.
------------
Closest hotel is Solomon Debebe Hotel.
------------
Closest hotel is Vahmoneh Lodge Vanimo.
------------
Hotel not found... skipping.
------------
Closest hotel is VS Villa.
------------
Closest hotel is شاطئ مايو.
------------
Closest hotel is Leumerus Bungalows.
------------
Closest hotel is Electric Power Hotel.
------------
Closest hotel is Hotel RIKMAN Continental.
------------
Closest hotel is ซันนี่ รีสอร์ท.
------------
Closest hotel is El Medina.
------------
Closest hotel is Timotel Hotel.
------------
Closest hotel is Jungjung Homestay.
------------
Closest hotel is Soneva Fushi.
------------
Closest hotel is Debright Motel.
------------
Closest hotel is Hilton Garden Inn Qidong.
------------
Closest hotel is Montana Hotel Syariah.
------------
Closest hotel is Oceano.
------------
Closest hotel is Chabakari - Am Doukhan.
------------
Closest hotel is Torch Hotel.
------------
Closest hotel is Groote Eylandt Lodge.
------------
Closest hotel is Courtyard by Marriott Port of Spain.
------------
Closest hotel is Hotel "Natalia".
------------
Hotel not found... skipping.
------------
Hotel not found... skipping.
------------
Closest hotel is Jinjiang Inn Zhoushan Putuo Shenjiamen.
------------
Closest hotel is OYO 884 Rumoh PMI Hotel.
------------
Closest hotel is Seri Simanggang Hotel.
------------
Closest hotel is Paradise Bay Resort.
------------
Closest hotel is Hotel Saratoga.
------------
Closest hotel is Hampton Inn & Suites Houston/League City.
------------
Closest hotel is Yurusato.
------------
Closest hotel is Crôa Mares Hotel.
------------
Closest hotel is East Arnhem Real Estate.
------------
Closest hotel is Maqna Hotel by Prasanthi.
------------
Closest hotel is Pazo de Verdes.
------------
Closest hotel is Mr.K.D. Mahant.
------------
Closest hotel is BBB Rooms Centro Tucurui PA.
------------
Closest hotel is Balochi Biryani.
------------
Closest hotel is Batalla’s Lodging House.
------------
Hotel not found... skipping.
------------
Closest hotel is Bora-Bora Pearl Beach Resort & Spa.
------------
Closest hotel is Pondok Wisata Elim.
------------
Closest hotel is Thank Inn Chain Hotel shanxi weinan linwei district jiefang road.
------------
Closest hotel is Ajoy.
------------
Closest hotel is Hostal Yunai.
------------
Closest hotel is Gostinitsa Kuryk - Otel' Dlya Vsekh Kategoriy Kliyentov ..
------------
Closest hotel is Condo Unit Ayala Land Corporation..
------------
Closest hotel is კურორტი ზეკარი/Resort Zekari.
------------
Closest hotel is 珠海粤财假日酒店.
------------
Closest hotel is Kost Pria.
------------
Closest hotel is Hotel le Carrefour.
------------
Closest hotel is Arribas Sintra Hotel.
------------
Closest hotel is Oumou Elghoura.
------------
Closest hotel is Hotel Ponta Verde Maceió.
------------
Hotel not found... skipping.
------------
Closest hotel is Screensaver.
------------
Hotel not found... skipping.
------------
Closest hotel is NUR.
------------
Closest hotel is BON Hotel Waterfront Richards Bay.
------------
Closest hotel is Best Western Ft. Walton Beachfront.
------------
Closest hotel is Kost annisa.
------------
Closest hotel is hotel la terminal.
------------
Closest hotel is Liceo Bolivariano 19 De Abril.
------------
Closest hotel is Hotel Serra da Chela.
------------
Closest hotel is Nusa Island Retreat.
------------
Closest hotel is Mantra Trilogy Cairns.
------------
Closest hotel is Hotel Arena Blanca.
------------
Closest hotel is Hotel Saigon-PT.
------------
Closest hotel is Reserva do Abiaí.
------------
Closest hotel is Hotel H1.
------------
Closest hotel is Hôtel Le Dronmi.
------------
Closest hotel is Osprey Beach Hotel.
------------
Closest hotel is Manav Residency.
------------
Closest hotel is Inubosaki Kanko Hotel.
------------
Closest hotel is Pousada Camboinha.
------------
Closest hotel is Green leaf.
------------
Closest hotel is Ejido La Pimienta.
------------
Closest hotel is Amate House.
------------
Closest hotel is Seydi oteli.
------------
Closest hotel is Moon light Furnished Units.
------------

Closest hotel is Salinas Park Resort Maçarico AP101.
------------
Closest hotel is Arman hotel.
------------
Closest hotel is Fairfield Inn & Suites by Marriott Key West.
------------
Closest hotel is Lorengau Harbourside Hotel.
------------
Closest hotel is Hotel Branco I.
------------
Closest hotel is Rumah Kuku Moimoi Shelly.
------------
Closest hotel is Grage Hotel Bengkulu.
------------
Closest hotel is City Bianjie Hotel Maanshan Dangtu.
------------
Closest hotel is Bluebay 08 satkosia Tarava.
------------
Hotel not found... skipping.
------------
Closest hotel is Uruna Bay Retreat.
------------
Closest hotel is Sol y Mar.
------------
Hotel not found... skipping.
------------
Closest hotel is Mishra resident and Advocate chamber,Bangalasahi,Athamallik,Angul.
------------
Closest hotel is Abaco Beach Resort.
------------
Closest hotel is Homestay Katakwi.
------------
Closest hotel is AVK events and catering.
------------
Closest hotel is Tibesti Hotel.
------------
Closest hotel is 帕米尔青年旅舍.
------------
Closest hotel is Black and Crystal Sand Campsite.
------------
Closest hotel is JABIR HOTEL.
------------
Closest hotel is Dhidhoo beach.
------------
Closest hotel is Hotel Les Arcades.
------------
Closest hotel is Avenue GuestHouse.
------------
Closest hotel is Hotel Ark 21.
------------
Hotel not found... skipping.
------------
Closest hotel is Resort Terra Paraiso.
------------
Closest hotel is Swiss-Belhotel Ambon.
------------
Closest hotel is Radisson Grenada Beach Resort.
------------
Closest hotel is Saigon Morin Hotel.
------------
Closest hotel is خوابگاه آبجی محدثه.
------------
Closest hotel is Pension Oaoa.
------------
Hotel not found... skipping.
------------
Hotel not found... skipping.
------------
Closest hotel is Diamond City Bungalow 13 pax by BeeStay near Broga.
------------
Closest hotel is Welcomhotel By ITC Hotels, Bay Island, Port Blair.
------------
Closest hotel is Ikathouse.
------------
Closest hotel is Dongyang Hotel.
------------
Closest hotel is Hotel La Bitta.
------------
Hotel not found... skipping.
------------
Hotel not found... skipping.
------------
Closest hotel is Kimbe Bay Hotel.
------------
Closest hotel is Khaled.
------------
Closest hotel is 景和商务酒店.
------------
Closest hotel is Delong Hotel.
------------
Closest hotel is Enashawa Lodge.
------------
Closest hotel is Ohio.
------------
Closest hotel is Red Crescent Cyclone Shelter Rashulpur.
------------
Closest hotel is Hotel Esperance.
------------
Closest hotel is OYO 3328 Hotel Mori.
------------
Closest hotel is Maringe Lagoon Lodge.
------------
Closest hotel is Hotel La Villa Couacou.
------------
Closest hotel is Halane Hotel and Restaurent.
------------
Closest hotel is WFP Guesthouse.
------------
Hotel not found... skipping.
------------
Closest hotel is Samrit Hotel.
------------
Closest hotel is Hôtel Mercure Rabat Sheherazade.
------------
Closest hotel is Amaloh Boutique Resort.
------------
Closest hotel is Dibbo areaمنطقة دبو.
------------
Closest hotel is SULIMAN INN.
------------
Closest hotel is Casa do Kiwliks.
------------
Closest hotel is Grand Kecubung Hotel.
------------
Closest hotel is Best Western Hotel Plaza Matamoros.
------------
Closest hotel is LT Aparthotel.
------------
Closest hotel is Casa Dora, Bubaque.
------------
Closest hotel is Pink Corral Bay Property.
------------
Closest hotel is Seaside Resort.
------------
Closest hotel is Embassy Suites by Hilton Dorado del Mar Beach Resort.
------------
Hotel not found... skipping.
------------
Closest hotel is Pousada dos Chapurys.
------------
Closest hotel is رابطة الفنانين الفلسطينيين.
------------
Closest hotel is LIKWALE LODGE.
------------
Closest hotel is Tarawa Boutique Hotel.
------------
Closest hotel is Heritage Park Hotel.
------------
Closest hotel is RUMBIA RESORT VILLA Paka Terengganu.
------------
Closest hotel is Tanna Lodge.
------------
Hotel not found... skipping.
------------
Closest hotel is Seagulls Inn Namatani.
------------
Closest hotel is La Quinta Inn by Wyndham Laredo I-35.
------------
Closest hotel is Shingu UI Hotel.
------------
Closest hotel is Axel Hotel Barcelona.
------------
Closest hotel is Guest House Aki.
------------
Closest hotel is Agapita M. Nicart.
------------
Closest hotel is Bustani B&B.
------------
Closest hotel is IU Hotel Shaoyang Xihu Road.
------------
Closest hotel is Leonardo Family Beach House 1.
------------
Closest hotel is Hotel Colombia Real - Cartagena.
------------
Closest hotel is فندق اجنحة كورال.
------------
Hotel not found... skipping.
------------
Closest hotel is OYO 598 Peony Hotel.
------------
Closest hotel is CeBlue Villas & Beach Resort.
------------
Closest hotel is Best Western Patriots Point.
------------
Closest hotel is La Ode Husein.
------------
Closest hotel is Lidera.
------------
Hotel not found... skipping.
------------
Closest hotel is Grand Vilia Hotel.
------------
Hotel not found... skipping.
------------
Closest hotel is Queens Guest Inn.
------------
Closest hotel is Vila Nova Hotel.
------------
Closest hotel is Penginapan Kim.
------------

In [20]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.isnull().sum()

City                   0
Country                0
Max Temp               0
Current Description    0
Lat                    0
Lng                    0
Hotel Name             0
dtype: int64

In [21]:
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Majene,ID,79.88,overcast clouds,-3.5403,118.9707,Kost Putri RABBANI
4,Kapaa,US,77.32,few clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
5,Bolobo,CD,83.89,light rain,-2.1667,16.2333,Hotel de Stephen
13,Gayeri,BF,85.82,light rain,12.6497,0.4931,
14,Atuona,PF,76.44,light rain,-9.8000,-139.0333,Hôtel Hiva Oa Hanakee Lodge
...,...,...,...,...,...,...,...
699,Tual,ID,81.75,overcast clouds,-5.6667,132.7500,Grand Vilia Hotel
700,Mundo Nuevo,MX,76.30,overcast clouds,18.7000,-95.5000,
701,Kontagora,NG,82.44,light rain,10.3999,5.4695,Queens Guest Inn
702,Ponta Delgada,PT,77.72,few clouds,37.7333,-25.6667,Vila Nova Hotel
703,Biak,ID,77.23,overcast clouds,-0.9131,122.8766,Penginapan Kim

In [22]:
nan_value = float("NaN")
hotel_df = hotel_df.replace("", nan_value)
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Majene,ID,79.88,overcast clouds,-3.5403,118.9707,Kost Putri RABBANI
4,Kapaa,US,77.32,few clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
5,Bolobo,CD,83.89,light rain,-2.1667,16.2333,Hotel de Stephen
13,Gayeri,BF,85.82,light rain,12.6497,0.4931,NaN
14,Atuona,PF,76.44,light rain,-9.8000,-139.0333,Hôtel Hiva Oa Hanakee Lodge
...,...,...,...,...,...,...,...
699,Tual,ID,81.75,overcast clouds,-5.6667,132.7500,Grand Vilia Hotel
700,Mundo Nuevo,MX,76.30,overcast clouds,18.7000,-95.5000,NaN
701,Kontagora,NG,82.44,light rain,10.3999,5.4695,Queens Guest Inn
702,Ponta Delgada,PT,77.72,few clouds,37.7333,-25.6667,Vila Nova Hotel
703,Biak,ID,77.23,overcast clouds,-0.9131,122.8766,Penginapan Kim

In [23]:
hotel_df.isnull().sum()

City                    0
Country                 0
Max Temp                0
Current Description     0
Lat                     0
Lng                     0
Hotel Name             28
dtype: int64

In [24]:
hotel_df = hotel_df.dropna()
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Majene,ID,79.88,overcast clouds,-3.5403,118.9707,Kost Putri RABBANI
4,Kapaa,US,77.32,few clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
5,Bolobo,CD,83.89,light rain,-2.1667,16.2333,Hotel de Stephen
14,Atuona,PF,76.44,light rain,-9.8000,-139.0333,Hôtel Hiva Oa Hanakee Lodge
17,Potiskum,NG,85.48,light rain,11.7091,11.0694,Tamir Hotel Ltd
...,...,...,...,...,...,...,...
696,Carutapera,BR,85.30,overcast clouds,-1.1950,-46.0200,Lidera
699,Tual,ID,81.75,overcast clouds,-5.6667,132.7500,Grand Vilia Hotel
701,Kontagora,NG,82.44,light rain,10.3999,5.4695,Queens Guest Inn
702,Ponta Delgada,PT,77.72,few clouds,37.7333,-25.6667,Vila Nova Hotel
703,Biak,ID,77.23,overcast clouds,-0.9131,122.8766,Penginapan Kim

In [25]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [28]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [30]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))